### ISSUE TITLE
What exactly are the benefits of this proposal?

### ISSUE THREAD

**Issue by theScottyJam** [ljharb/proposal-get-intrinsic#8]
This issue is branched out from #7, because it's sort of unrelated to the other issue's original topic.

The question is: What is the end goal this proposal is hoping to provide? In the other issue, I had previously laid out the following benefits that this proposal provides.
1. It's easier than current solutions
2. Memory/bundle size? Because you don't have to hold a bunch of local references.
3. The avoidance of eval to get values that otherwise require the use of eval, because it might use syntax that's unsupported.

Point 1 is sort of irrelevant because this proposal explicitly states that its purpose is to not improve the ergonomics of this "pre-caching functions to prevent tampering" pattern.

I realized later that point 2 isn't very strong either. The big example for this proposal is your situation @ljharb's, where you have many shims out there that depend on a get-intrinsic package. I think this situation is a bit unique - not only do you care about trying to grab a snapshot of the current state of things before they get modified - you're wanting _all_ of your packages to use the snapshot that your first-loaded package grabs, in case something changes between the two packages being loaded.

Not many people are in a situation where this is even possible. You're only able to do that because you expect people to be using many of your packages at once. You mentioned that the cost of anyone using your packages is at least "9.7KB" because they additionally have to download this get-intrinsics package, though I wouldn't be surprised if most of that get-intrinsic package is untouched by most of your shims - they only need a handful of the cached functions to do what they need to do.

If a more direct approach was taken instead, where you're manually locally caching each function you need in each package, then I would expect that extra download size would largely vanish. I don't think we can say that this is "not an option", because, for a lot of people, it's "the only option" - they don't have a way to share cached functions between their libraries, because they have no reason to expect that a user will likely use multiple libraries produced by them at once.

Point 3 doesn't seem very strong either. If you're only locally caching what your library needs, then your package wouldn't need to unnecessarily contain evals within it. Either it depends on that syntax, in which case you must be using a new enough version of Javascript for the shim to work, or it does not depend on the syntax, in which case, no eval necessary.

To summarize, the target audience of this proposal seems to be for:
* People who expect it to be common for end-users to be using multiple of their packages together
* People who want to protect against intrinsics being modified
* People who care so strongly about the previous point that they want their package to try and get the state of their environment before it's the package has even loaded, by borrowing it from whatever package loaded first.

Again, a lot of people aren't even capable of doing the last bullet point, even if they wanted to get the global state at an earlier phase, so it seems odd to try and provide a feature that's specifically made to help those who are in that group. Why not just let packages accept the state in which things are currently at when they first run, instead of encouraging people to try and reach for the state of things before they even got loaded?

**Comment by ljharb** [comment]
Point 1 isn’t irrelevant - ease and ergonomics aren’t exactly the same thing.

Having to cache individual functions that are needed, directly, means that to be robust, each of these packages can’t be lazily loaded - they need to all be evaluated eagerly, before untrusted code. By using the get-intrinsics package or by having this built into the language, instead of hundreds of packages needing to run first, only one does

i completely agree that the number of users who will use this api directly is very small. However, the number of users that are transitively affected by this api is very large - far, far larger than other niche language features (even Proxy, I’d bet).

**Comment by theScottyJam** [comment]
And what happens when a user only wants to use one of your libraries, and they want it lazy-loaded after they've loaded some unsafe packages?

The fundamental issue here is the fact that anyone can mess with globals and affect everyone else. The solution is realms. What you're doing is just trying to plug as many holes as you can reach without using realms. What you're proposing is a way to plug just a couple more holes without a bandwidth cost.

The question is - is it worth adding a new feature whose only purpose is to allow people to reach those couple of extra holes with no bandwidth penalty? Is it even worth it to try and plug those last hard-to-reach holes in the first place?

Obviously, you think so and I don't. 🤷‍♂️️

**Comment by ljharb** [comment]
This is also adding new functionality - your third item, non-eval and non-procedural access to intrinsics that otherwise require eval or procedural code.

With any feature, some people may not see the need for it, but unless there’s a cost to pay, those folks typically don’t obstruct solutions to others’ problems. What cost are you concerned with paying that motivates filing this issue?

**Comment by zloirock** [comment]
Since `getIntrinsic` is not protected from overwriting, I don't see any benefits for polyfills even in caching of `getIntrinsic` instead of cashing required built-ins. At first, it's for @ljharb calming in not real-life cases like [this](https://github.com/tarruda/has/pull/16).

However, the real-life benefit of `getIntrinsic` for polyfills is access to something that is not available in usual built-ins access. For example, now we can't get access to `%AsyncIteratorPrototype%` without the creation of async generators. The only way is `Object.getPrototypeOf(Object.getPrototypeOf(Object.getPrototypeOf(async function * (){}())))
`. But since polyfills should work even in engines without async generators support, we are forced to use something like `Function` constructor that is unacceptable since it will break CSP. That makes universal polyfill of [async iterator helpers](https://github.com/tc39/proposal-iterator-helpers) impossible without breaking CSP. `getIntrinsic` could fix it. I think this use case should be added to the README.

**Comment by theScottyJam** [comment]
@zloirock - it does mention csp in the README, but it doesn't give any concrete examples (a concrete example would be a nice addition).

The thing is, I'm not sure how strong of a motivation this is. One day, IE will die, and so will older version of Javascript, and there won't be a need for polyfills to support es5 days anymore. Javascript proposals are always trying to look ahead at how we want the future of Javascript to look, not how we want things to be done _now_.

@ljharb - There's lots of things lots of people want to add to the language that doesn't affect anyone else. You're right that it really doesn't affect me much if this proposal goes through or not, and there's certainly a lot lower bar to adding new functions over syntax. But, the bar is still there, and I don't want to be unnecessarily bloating Javascript with functions that I don't think add value to the language. There's still a complexity cost to this function, even if it's just a function, like the fact that polyfills now have an additional thing they need to update.

And what you seem to perceive as a huge problem, I see as simply part of the day-to-day life of the average developer. If you, or one of your libraries delete Function.prototype.call, and your app will be broken, even if one of your polyfills tries as hard as it possibly can to defend against it. What problem has been solved? I know I'm not going to convince you on anything in relation to this point, and that's fine, we'll disagree here, and if you choose to go and defend your polyfills as much as possible, that's fine, it's your code, but if you're also going to try and make language changes based on the idea that "A library defending against globalThis changes is good and is a net positive when library authors do it as much as humanly possible", well then, we'll need to try and discuss if this underlying theory is actually a valid one or not.

**Comment by theScottyJam** [comment]
Let me give just one such reason why it might not be as good to defend against it: It obfuscates your own code. This means that
* It's harder for other developers to go into it and help out with bug-fixes and what not
* It's harder for anyone who's using your polyfill to follow it and figure out what it does (have you ever snooped into the libraries you're using? e.g. perhaps you've run into a bug and you were trying to track it down).
* It's easier for the developer to create bugs, due to the added complexity.
* It adds to the overall bundle size.

And the benefit is that when a user destroys their own globalThis, at least the error won't be thrown from within this particular polyfill, it'll get thrown inside some other library they use instead. (I actually see this as a con as well though - because I'd rather that everything tried to be as noisy as possible when things go wrong).

Admittedly, the pros are pretty minor, and some of them are just personal preferences of a package author (e.g. perhaps they don't care if people contribute or not). But, the cons are pretty minor as well (or, if you're like me, you actually count the only con as a pro as well).

**Comment by ljharb** [comment]
@theScottyJam the code (all my polyfills) already looks like this. This proposal makes those things *better* by making it a standard part of the language instead of an arbitrary pattern.

If the error is thrown from another library, then an issue can be filed on that one, and eventually the majority of libraries can be robust in this manner, although that will take a combination of other proposals before it's ergonomic (and thus, widely adopted).

The reality is that even *if* I'm the only developer who meets these requirements, that still accounts for a tenth of npm's weekly download traffic, so my packages alone still constitute a significant percentage of the world's javascript usage. Obviously I do not believe I will be the only developer who uses this functionality!

I'm saying that if you look at the number of users who will be _helped_, directly or indirectly, by this proposal, it is quite a large population.

The questions in the issue seem answered, and I don't think this is a productive place to simply go back and forth about things we disagree on - is it ok if this is closed?

**Comment by theScottyJam** [comment]
> The questions in the issue seem answered, and I don't think this is a productive place to simply go back and forth about things we disagree on - is it ok if this is closed?

You're right that we're probably not going to move each other on this, so I'd be ok if we closed this. But first - I want to explore something you mentioned.

> If the error is thrown from another library, then an issue can be filed on that one, and eventually the majority of libraries can be robust in this manner, although that will take a combination of other proposals before it's ergonomic (and thus, widely adopted).

I didn't realize that you're thinking of there being other proposals after this that would actually improve the ergonomics of a library defending against globalThis tampering (though, I guess the README suggested something like this as well). Perhaps this isn't the place for this discussion, (but I'm not sure where else would be), but, how could we actually achieve this? I'm curious how this proposal fits into the overall plan to provide easy defenses against this issue - knowing the big picture might make it easier to understand where this specific proposal fits in (or, it could let us know if this proposal would just become obsolete by a better proposal that's yet to come).

**Comment by ljharb** [comment]
It’s not yet clear exactly what it would look like. However, this proposal, combined with the pipe operator and a method extraction/.call syntax, would go a very long way.

Happy to keep discussing, but closing per above.

**Comment by zloirock** [comment]
@theScottyJam sure I mean a correct example.

> The thing is, I'm not sure how strong of a motivation this is. One day, IE will die, and so will older version of Javascript, and there won't be a need for polyfills to support es5 days anymore. Javascript proposals are always trying to look ahead at how we want the future of Javascript to look, not how we want things to be done now.

How it's related to IE and ES5? Async generators in this example were added 2018, iterator helpers maybe will be added in 2023, features that add new syntax and related built-ins will be added in the future regularly. Old browsers will always be, bugs will happen even in modern browsers, new language features will appear regularly and anyway they will appear in browsers with a delay - so, if we want to to use modern JS in development and minimize possible problems, polyfills with us for a long time.

**Comment by ljharb** [comment]
Exactly this; as long as the language keeps evolving, polyfills and transpilers will remain equally relevant.

**Comment by theScottyJam** [comment]
Good point @zloirock - I obviously didn't think through that point well. Thanks.
